name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            asset_name: ip-check-tool-windows.exe
            pyinstaller_args: --windowed
          - os: ubuntu-latest
            asset_name: ip-check-tool-linux
            pyinstaller_args: ''
          - os: macos-latest
            asset_name: ip-check-tool-macos
            pyinstaller_args: ''

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install tk
        
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install python-tk
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile ${{ matrix.pyinstaller_args }} --add-data "check.py:." --name ${{ matrix.asset_name }} main.py

    # 添加文件权限
    - name: Make executables executable
      if: matrix.os != 'windows-latest'
      run: chmod +x dist/${{ matrix.asset_name }}

    # 压缩构建产物
    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: '${{ matrix.asset_name }}.zip'
        directory: dist/

    # 上传构建产物
    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/${{ matrix.asset_name }}.zip
      if: startsWith(github.ref, 'refs/tags/') 